# Generated by Django 5.1.5 on 2025-01-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='crust',
            field=models.CharField(choices=[('normal', 'Normal'), ('thick', 'Thick'), ('thin', 'Thin'), ('gluten_free', 'Gluten-Free')], max_length=20),
        ),
    ]
