# Generated by Django 5.1.5 on 2025-02-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0005_pizzaorder_city_pizzaorder_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaorder',
            name='card_cvv',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='card_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='card_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='expiry_date',
            field=models.CharField(default='', max_length=5),
        ),
    ]
