# Generated by Django 5.1.5 on 2025-02-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0006_pizzaorder_card_cvv_pizzaorder_card_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='expiry_date',
            field=models.CharField(default='', max_length=5),
        ),
    ]
