# Generated by Django 5.1.5 on 2025-02-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0007_alter_pizzaorder_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='expiry_date',
            field=models.CharField(default='', max_length=5),
        ),
    ]
